meta:
  environment: (( merge ))
  proxy_floating_ip: (( merge ))

  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest

jobs:
- name: proxy
  instances: 1
  networks:
  - name: round_robin_app1
    default:
    - dns
    - gateway
    static_ips: (( static_ips(0) ))
  - name: floating
    static_ips:
    - (( meta.proxy_floating_ip ))
- name: app
  instances: 2
  networks:
  - name: round_robin_app1
    static_ips: (( static_ips(1, 2) ))

compilation:
  cloud_properties:
    instance_type: c3.large

resource_pools:
- name: small_z1
  cloud_properties:
    instance_type: m1.medium

networks:
- name: floating
  type: vip
  <<: (( merge ))
- name: round_robin_app1
  type: manual
  <<: (( merge ))
