meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
- name: proxy
  template: proxy
  instances: 1
  resource_pool: small_z1
  networks: (( merge ))
  persistent_disk: 0
- name: app
  template: app
  instances: 2
  resource_pool: small_z1
  networks: (( merge ))
  persistent_disk: 0
  update:
    canaries: 10

networks: (( merge ))

properties:
  proxy:
    hosts: (( jobs.app.networks.[0].static_ips ))
