#!/bin/bash

set -e

if [ -z "$1" ]; then
  echo "usage: $0 templates/stub.yml"
  exit 1
fi

templates=$(dirname $0)

spiff merge \
  $templates/deployment.yml \
  $templates/jobs.yml \
  $templates/infrastructure-aws-ec2.yml \
  $*
